### ISSUE TITLE
doesnt work on rigify 6.6 and 6.5

### ISSUE THREAD

**Issue by AnityEx** [Plyrolith/rigify_bendy#9]
tested on blender 3.1 - 3.2 - 3.3 - 3.4 and 3.5 wich for some reason 3.5 worked without errors until i tried adding a rig and the menu was empty 

heres the error i get on a brand new install of blender 3.1.2 if i try to add the bendify extension to rigify

`Python: Traceback (most recent call last):
  File "C:\Program Files\BLauncher\stable\blender-3.1.2+stable.cc66d1020c3b\3.1\scripts\addons\rigify\metarig_menu.py", line 228, in get_external_metarigs
    get_metarigs(metarigs['external'], base_dir, base_path)
  File "C:\Program Files\BLauncher\stable\blender-3.1.2+stable.cc66d1020c3b\3.1\scripts\addons\rigify\metarig_menu.py", line 70, in get_metarigs
    get_metarigs(metarigs[f], base_dir, base_path, path=[*path, f], nested=True)  # "" adds a final slash
  File "C:\Program Files\BLauncher\stable\blender-3.1.2+stable.cc66d1020c3b\3.1\scripts\addons\rigify\metarig_menu.py", line 74, in get_metarigs
    module = get_resource('.'.join([*base_path, *path, f]))
  File "C:\Program Files\BLauncher\stable\blender-3.1.2+stable.cc66d1020c3b\3.1\scripts\addons\rigify\utils\rig.py", line 128, in get_resource
    module = importlib.import_module(resource_name)
  File "C:\Program Files\BLauncher\stable\blender-3.1.2+stable.cc66d1020c3b\3.1\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\wesle\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\rigify\bendify_main\__init__.py", line 16, in <module>
    from .rigify_ui import *
  File "C:\Users\wesle\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\rigify\bendify_main\rigify_ui.py", line 2, in <module>
    from rigify.ui import DATA_PT_rigify_buttons, DATA_PT_rigify_bone_groups, BONE_PT_rigify_buttons
ImportError: cannot import name 'DATA_PT_rigify_buttons' from 'rigify.ui' (C:\Program Files\BLauncher\stable\blender-3.1.2+stable.cc66d1020c3b\3.1\scripts\addons\rigify\ui.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\BLauncher\stable\blender-3.1.2+stable.cc66d1020c3b\3.1\scripts\addons\rigify\feature_set_list.py", line 237, in execute
    addon_prefs.update_external_rigs()
  File "C:\Program Files\BLauncher\stable\blender-3.1.2+stable.cc66d1020c3b\3.1\scripts\addons\rigify\__init__.py", line 227, in update_external_rigs
    metarig_menu.get_external_metarigs(set_list)
  File "C:\Program Files\BLauncher\stable\blender-3.1.2+stable.cc66d1020c3b\3.1\scripts\addons\rigify\metarig_menu.py", line 230, in get_external_metarigs
    print("Rigify Error: Could not load feature set '%s' metarigs: exception occurred.\n" % (feature_set))
NameError: name 'feature_set' is not defined. Did you mean: 'feature_set_list'?

location: <unknown location>:-1

`

**Comment by Plyrolith** [comment]
Hey! Sadly this Rigify extension was never updated/tested for Blender 3.x and anything after. At this point, I would call it deprecated, since the bendy bones upgrades rendered the extension's features obsolete/incompatible.
I suggest you try CloudRig instead, where all limb modules come with similar functionality (& more!).
